# Generated by Django 3.2.7 on 2021-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='abbreviation',
            field=models.CharField(default='NIL', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(default='NIL', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='auctions.categories'),
        ),
    ]
