# Generated by Django 3.2.7 on 2021-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211006_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='abbreviation',
            field=models.CharField(default='NUL', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(default='NULL', max_length=30, unique=True),
        ),
    ]
